run:
  timeout: 5m

linters:
  enable:
    - ineffassign
    - misspell
    - gocyclo
    - goimports
    - govet
    - gofmt
    - goimports
    - godot
    - predeclared
    - unconvert
    - whitespace
    - unused
    - unconvert
    - dogsled
    - misspell
    - paralleltest
    - prealloc
    - importas
    - asciicheck
    - stylecheck
    - durationcheck
    - unparam
    - goprintffuncname
    - forcetypeassert

severity:
  default-severity: warning

#linters-settings:
#  revive:
#    severity: error
#    rules:
#      - name: exported
#      - name: if-return
#        disabled: true